### ISSUE TITLE
Create Issue Templates

### ISSUE THREAD

**Issue by leecalcote** [layer5io/service-mesh-performance-specification#23]
This repository would benefit from the same set of issue templates found in the other Layer5 repos.

@gunjanmimo or @ashiscs, would you mind assisting here?

**Comment by leecalcote** [comment]
@Vineet-Sharma29 you might want to try your hand at this. It involves copying the GitHub issue templates from https://github.com/layer5io/meshery/tree/master/.github/ISSUE_TEMPLATE and pasting into a new `./github/ISSUE_TEMPLATE` folder in this repo.

**Comment by Vineet-Sharma29** [comment]
Sure!

**Comment by leecalcote** [comment]
Thank you, @Vineet-Sharma29
