### ISSUE TITLE
Create a fifth specification to separate out workload metadata

### ISSUE THREAD

**Issue by leecalcote** [layer5io/service-mesh-performance-specification#27]
**Current Behavior**
The specification nominally considers for the description and all of the interesting metadata of the application (e.g. application name, application version, helm chart version #, and so on).

**Desired Behavior**
The definition of the workload profile definition should be expanded on. 

Consider definitions like CNAB, Docker Compose, Helm, and so on.

**Comment by kushthedude** [comment]
I will look into it.
