### ISSUE TITLE
Enum for `service_mesh` type

### ISSUE THREAD

**Issue by leecalcote** [layer5io/service-mesh-performance-specification#33]
To guarantee compatibility between SMPS implementations, we may want to use an enum for `service_mesh`.

_Originally posted by @leecalcote in https://github.com/layer5io/service-mesh-performance-specification/pull/31_

**Comment by kanishkarj** [comment]
@leecalcote , wouldn't we also want to consider the difference versions of the service meshes?

**Comment by leecalcote** [comment]
@kanishkarj Yes, for certain. For sure.
