### ISSUE TITLE
Remove smps.yaml from this repo

### ISSUE THREAD

**Issue by leecalcote** [layer5io/service-mesh-performance-specification#39]
**Description**
The smps.yaml has been displaced by smps.proto and sm.proto.

**Expected Behavior**
[smps.yaml](https://github.com/layer5io/service-mesh-performance-specification/blob/master/smps.yaml) should be deleted.

**Comment by Dhiraj240** [comment]
@leecalcote I will work on this issue.

**Comment by leecalcote** [comment]
@Dhiraj240 thank you much. Yes, indeed. Simply that, if you would.

**Comment by kushthedude** [comment]
@leecalcote Shouldn't smps.yaml should work as an ideal input for specification ?

**Comment by leecalcote** [comment]
Yes, although, my impression was that we have accounted for each of these parameters. I could be mistaken.

**Comment by Dhiraj240** [comment]
Yeah, will do this

**Comment by kushthedude** [comment]
The yaml file can work as a source of truth like how should I specify my data, as in the protobuf file I have only mentioned the type of data not the format like for example of data/time.
