### ISSUE TITLE
[Chore] Reconcile img and assets folders; Consolidate to img folder.

### ISSUE THREAD

**Issue by leecalcote** [layer5io/service-mesh-performance-specification#42]
**Current Behavior**
The `img/readme` and the `/assets` folders are duplicative (for the same purpose). These two folders need to be reconciled by deduplicating their contents.

**Desired Behavior**
All of these assets are consolidated into the `/img/readme` folder.

**Comment by leecalcote** [comment]
@itsapoorvj, would you like to tackle this one?

**Comment by itsapoorvj** [comment]
Sure, I will do that.
