### ISSUE TITLE
Create website for SMPS

### ISSUE THREAD

**Issue by leecalcote** [layer5io/service-mesh-performance-specification#45]
**Current Behavior**
Today, this initiative is best represented at https://layer5.io/performance. This initiative is in need of a dedicated site to describe its goals, how to get involved, and so on.

**Desired Behavior**
A new site created using Jekyll and GitHub Pages.

---
**Resources**
See https://meshery.io as an example.

**Comment by kushthedude** [comment]
I was really waiting for this 🤩

**Comment by leecalcote** [comment]
[Site ideas doc](https://docs.google.com/document/d/1tDGCiAh5ATeRCNAyTRzV4bVbKEy9k1QsakNiK7feGCc/edit?ts=5f0e0d9b)

**Comment by kushthedude** [comment]
Closed in #57
