### ISSUE TITLE
[Docs] Create contributing docs for the smps-spec.io site

### ISSUE THREAD

**Issue by leecalcote** [layer5io/service-mesh-performance-specification#68]
**Current State:**
Site is created by Jekyll.
Site runs on GitHub Pages.
Site sits in this repo under /docs.

**Desired State:**
Contributing docs are needed here. The same docs used for either layer5.io or meshery.io can be copied.

---
**Contributor Resources**
- [Meshery documentation site](https://meshery.layer5.io/docs/)
- [Meshery documentation source](https://github.com/layer5io/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

**Comment by PluckyPrecious** [comment]
@leecalcote should I take this up?

**Comment by leecalcote** [comment]
@PluckyPrecious that would be nice. Yes, please.
