### ISSUE TITLE
[CI] Add releasedrafter to this repo

### ISSUE THREAD

**Issue by leecalcote** [layer5io/service-mesh-performance-specification#76]
**Description**
Leverage (copy) the releasedrafter configuration from the `meshery` repo.

- https://github.com/layer5io/meshery/blob/master/.github/workflows/release-drafter.yml

**Comment by JubayerJoy** [comment]
I have Leveraged the releasedrafter configuration from the ```meshery``` repo to this Repo.
Please review.

_Note:_ There were some _sign-off issues_ in the first two PRs, I've corrected them in the last one.
